# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
title = "Esther's Blog"
weight = 1

[zh-cn]
languageName = "简体中文"
languagedirection = "ltr"
title = "以丝忒的博客"
weight = 1
